apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zgw-posix.fullname" . }}-user
  labels:
    {{- include "zgw-posix.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY: {{ .Values.auth.accessKey | b64enc }}
  SECRET_KEY: {{ .Values.auth.secretKey | b64enc }}
