apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "zgw-posix.fullname" .) }}
  labels:
    {{- include "zgw-posix.labels" . | nindent 4 }}
  {{- if and .Values.podTLS.enabled .Values.podTLS.openshiftServingCert }}
  annotations:
    # OCP injects a cluster-signed TLS cert into this Secret automatically.
    service.beta.openshift.io/serving-cert-secret-name: {{ include "zgw-posix.fullname" . }}-serving-cert
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: s3
      protocol: TCP
      name: s3
    {{- if .Values.podTLS.enabled }}
    - port: 443
      targetPort: s3-https
      protocol: TCP
      name: s3-https
    {{- end }}
  selector:
    {{- include "zgw-posix.selectorLabels" . | nindent 4 }}
